substitutions:
  _IMAGE_NAME: "itacap-service"
  _REPO_NAME: "itacap"
  _IMAGE_TAG: "vMAJOR.MINOR.PATCH"
  _REGION: "us-east4"
  _SERVICE_NAME: "itacap-service"

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'  # Remove this if your service should be private

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
