CREATE SCHEMA IF NOT EXISTS itac_ap;
USE itac_ap;

-- -- tables -- --
-- sic codes
create table sic_code
(
    code           VARCHAR(30) PRIMARY KEY COMMENT 'Unique key id for table',
    industry_title VARCHAR(255) NOT NULL COMMENT 'Industry title',
    status_cd      VARCHAR(15)  NOT NULL DEFAULT 'active' COMMENT 'Status (active,inactive)',
    create_user    VARCHAR(50)  NOT NULL COMMENT 'Create user',
    create_dt      TIMESTAMP    NOT NULL COMMENT 'Date/time of creation',
    update_user    VARCHAR(50) COMMENT 'Update user',
    update_dt      TIMESTAMP COMMENT 'Date/time of last update'
);

INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0111','Wheat','active','seth','2025-05-23 13:38:28',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0112','Rice','active','seth','2025-05-23 13:38:28',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0115','Corn','active','seth','2025-05-23 13:38:28',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0116','Soybeans','active','seth','2025-05-23 13:38:29',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0119','Cash Grains, Not Elsewhere Classified','active','seth','2025-05-23 13:38:29',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0131','Cotton','active','seth','2025-05-23 13:38:29',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0132','Tobacco','active','seth','2025-05-23 13:38:30',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0133','Sugarcane and Sugar Beets','active','seth','2025-05-23 13:38:30',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0134','Irish Potatoes','active','seth','2025-05-23 13:38:31',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0139','Field Crops, Except Cash Grains, Not Elsewhere Classified','active','seth','2025-05-23 13:38:31',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0161','Vegetables and Melons','active','seth','2025-05-23 13:38:31',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0171','Berry Crops','active','seth','2025-05-23 13:38:32',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0172','Grapes','active','seth','2025-05-23 13:38:32',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0173','Tree Nuts','active','seth','2025-05-23 13:38:32',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0174','Citrus Fruits','active','seth','2025-05-23 13:38:33',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0175','Deciduous Tree Fruits','active','seth','2025-05-23 13:38:33',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0179','Fruits and Tree Nuts, Not Elsewhere Classified','active','seth','2025-05-23 13:38:33',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0181','Ornamental Floriculture and Nursery Products','active','seth','2025-05-23 13:38:34',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0182','Food Crops Grown Under Cover','active','seth','2025-05-23 13:38:34',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0191','General Farms, Primarily Crop','active','seth','2025-05-23 13:38:34',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0211','Beef Cattle Feedlots','active','seth','2025-05-23 13:38:35',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0212','Beef Cattle, Except Feedlots','active','seth','2025-05-23 13:38:35',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0213','Hogs','active','seth','2025-05-23 13:38:35',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0214','Sheep and Goats','active','seth','2025-05-23 13:38:36',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0219','General Livestock, Except Dairy and Poultry','active','seth','2025-05-23 13:38:36',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0241','Dairy Farms','active','seth','2025-05-23 13:38:36',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0251','Broiler, Fryer, and Roaster Chickens','active','seth','2025-05-23 13:38:37',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0252','Chicken Eggs','active','seth','2025-05-23 13:38:37',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0253','Turkeys and Turkey Eggs','active','seth','2025-05-23 13:38:37',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0254','Poultry Hatcheries','active','seth','2025-05-23 13:38:38',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0259','Poultry and Eggs, Not Elsewhere Classified','active','seth','2025-05-23 13:38:38',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0271','Fur-Bearing Animals and Rabbits','active','seth','2025-05-23 13:38:38',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0272','Horses and Other Equines','active','seth','2025-05-23 13:38:39',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0273','Animal Aquaculture','active','seth','2025-05-23 13:38:39',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0279','Animal Specialties, Not Elsewhere Classified','active','seth','2025-05-23 13:38:40',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0291','General Farms, Primarily Livestock and Animal Specialties','active','seth','2025-05-23 13:38:40',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0711','Soil Preparation Services','active','seth','2025-05-23 13:38:40',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0721','Crop Planting, Cultivating, and Protecting','active','seth','2025-05-23 13:38:41',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0722','Crop Harvesting, Primarily by Machine','active','seth','2025-05-23 13:38:41',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0723','Crop Preparation Services for Market, Except Cotton Ginning','active','seth','2025-05-23 13:38:41',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0724','Cotton Ginning','active','seth','2025-05-23 13:38:41',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0741','Veterinary Services for Livestock','active','seth','2025-05-23 13:38:42',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0742','Veterinary Services for Animal Specialties','active','seth','2025-05-23 13:38:42',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0751','Livestock Services, Except Veterinary','active','seth','2025-05-23 13:38:43',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0752','Animal Specialty Services, Except Veterinary','active','seth','2025-05-23 13:38:43',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0761','Farm Labor Contractors and Crew Leaders','active','seth','2025-05-23 13:38:43',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0762','Farm Management Services','active','seth','2025-05-23 13:38:44',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0781','Landscape Counseling and Planning','active','seth','2025-05-23 13:38:44',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0782','Lawn and Garden Services','active','seth','2025-05-23 13:38:44',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0783','Ornamental Shrub and Tree Services','active','seth','2025-05-23 13:38:45',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0811','Timber Tracts','active','seth','2025-05-23 13:38:45',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0831','Forest Nurseries and Gathering of Forest Products','active','seth','2025-05-23 13:38:45',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0851','Forestry Services','active','seth','2025-05-23 13:38:46',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0912','Finfish','active','seth','2025-05-23 13:38:46',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0913','Shellfish','active','seth','2025-05-23 13:38:46',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0919','Miscellaneous Marine Products','active','seth','2025-05-23 13:38:47',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0921','Fish Hatcheries and Preserves','active','seth','2025-05-23 13:38:47',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('0971','Hunting and Trapping, and Game Propagation','active','seth','2025-05-23 13:38:47',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1011','Iron Ores','active','seth','2025-05-23 13:38:47',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1021','Copper Ores','active','seth','2025-05-23 13:38:48',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1031','Lead and Zinc Ores','active','seth','2025-05-23 13:38:48',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1041','Gold Ores','active','seth','2025-05-23 13:38:48',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1044','Silver Ores','active','seth','2025-05-23 13:38:49',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1061','Ferroalloy Ores, Except Vanadium','active','seth','2025-05-23 13:38:49',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1081','Metal Mining Services','active','seth','2025-05-23 13:38:49',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1094','Uranium-Radium-Vanadium Ores','active','seth','2025-05-23 13:38:50',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1099','Miscellaneous Metal Ores, Not Elsewhere Classified','active','seth','2025-05-23 13:38:52',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1221','Bituminous Coal and Lignite Surface Mining','active','seth','2025-05-23 13:40:00',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1222','Bituminous Coal Underground Mining','active','seth','2025-05-23 13:40:00',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1231','Anthracite Mining','active','seth','2025-05-23 13:40:01',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1241','Coal Mining Services','active','seth','2025-05-23 13:40:01',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1311','Crude Petroleum and Natural Gas','active','seth','2025-05-23 13:40:01',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1321','Natural Gas Liquids','active','seth','2025-05-23 13:40:02',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1381','Drilling Oil and Gas Wells','active','seth','2025-05-23 13:40:02',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1382','Oil and Gas Field Exploration Services','active','seth','2025-05-23 13:40:02',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1389','Oil and Gas Field Services, Not Elsewhere Classified','active','seth','2025-05-23 13:40:03',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1411','Dimension Stone','active','seth','2025-05-23 13:40:03',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1422','Crushed and Broken Limestone','active','seth','2025-05-23 13:40:03',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1423','Crushed and Broken Granite','active','seth','2025-05-23 13:40:04',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1429','Crushed and Broken Stone, Not Elsewhere Classified','active','seth','2025-05-23 13:40:04',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1442','Construction Sand and Gravel','active','seth','2025-05-23 13:40:04',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1446','Industrial Sand','active','seth','2025-05-23 13:40:05',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1455','Kaolin and Ball Clay','active','seth','2025-05-23 13:40:05',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1459','Clay, Ceramic, and Refractory Minerals, Not Elsewhere Classified','active','seth','2025-05-23 13:40:05',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1474','Potash, Soda, and Borate Minerals','active','seth','2025-05-23 13:40:06',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1475','Phosphate Rock','active','seth','2025-05-23 13:40:06',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1479','Chemical and Fertilizer Mineral Mining, Not Elsewhere Classified','active','seth','2025-05-23 13:40:06',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1481','Nonmetallic Minerals Services, Except Fuels','active','seth','2025-05-23 13:40:07',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1499','Miscellaneous Nonmetallic Minerals, Except Fuels','active','seth','2025-05-23 13:40:07',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1521','General Contractors-Single-Family Houses','active','seth','2025-05-23 13:40:07',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1522','General Contractors-Residential Buildings, Other Than Single-Family','active','seth','2025-05-23 13:40:08',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1531','Operative Builders','active','seth','2025-05-23 13:40:08',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1541','General Contractors-Industrial Buildings and Warehouses','active','seth','2025-05-23 13:40:08',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1542','General Contractors-Nonresidential Buildings, Other than Industrial Buildings and Warehouses','active','seth','2025-05-23 13:40:09',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1611','Highway and Street Construction, Except Elevated Highways','active','seth','2025-05-23 13:40:09',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1622','Bridge, Tunnel, and Elevated Highway Construction','active','seth','2025-05-23 13:40:09',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1623','Water, Sewer, Pipeline, and Communications and Power Line Construction','active','seth','2025-05-23 13:40:10',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1629','Heavy Construction, Not Elsewhere Classified','active','seth','2025-05-23 13:40:10',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1711','Plumbing, Heating and Air-Conditioning','active','seth','2025-05-23 13:40:10',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1721','Painting and Paper Hanging','active','seth','2025-05-23 13:40:11',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1731','Electrical Work','active','seth','2025-05-23 13:40:11',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1741','Masonry, Stone Setting, and Other Stone Work','active','seth','2025-05-23 13:40:11',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1742','Plastering, Drywall, Acoustical, and Insulation Work','active','seth','2025-05-23 13:40:12',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1743','Terrazzo, Tile, Marble, and Mosaic Work','active','seth','2025-05-23 13:40:12',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1751','Carpentry Work','active','seth','2025-05-23 13:40:12',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1752','Floor Laying and Other Floor Work, Not Elsewhere Classified','active','seth','2025-05-23 13:40:13',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1761','Roofing, Siding, and Sheet Metal Work','active','seth','2025-05-23 13:40:13',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1771','Concrete Work','active','seth','2025-05-23 13:40:13',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1781','Water Well Drilling','active','seth','2025-05-23 13:40:14',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1791','Structural Steel Erection','active','seth','2025-05-23 13:40:14',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1793','Glass and Glazing Work','active','seth','2025-05-23 13:40:14',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1794','Excavation Work','active','seth','2025-05-23 13:40:15',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1795','Wrecking and Demolition Work','active','seth','2025-05-23 13:40:15',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1796','Installation or Erection of Building Equipment, Not Elsewhere','active','seth','2025-05-23 13:40:16',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('1799','Special Trade Contractors, Not Elsewhere Classified','active','seth','2025-05-23 13:40:16',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2011','Meat Packing Plants','active','seth','2025-05-23 13:40:16',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2013','Sausages and Other Prepared Meat Products','active','seth','2025-05-23 13:40:17',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2015','Poultry Slaughtering and Processing','active','seth','2025-05-23 13:40:17',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2021','Creamery Butter','active','seth','2025-05-23 13:40:17',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2022','Natural, Processed, and Imitation Cheese','active','seth','2025-05-23 13:40:18',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2023','Dry, Condensed, and Evaporated Dairy Products','active','seth','2025-05-23 13:40:18',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2024','Ice Cream and Frozen Desserts','active','seth','2025-05-23 13:40:18',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2026','Fluid Milk','active','seth','2025-05-23 13:40:19',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2032','Canned Specialties','active','seth','2025-05-23 13:40:19',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2033','Canned Fruits, Vegetables, Preserves, Jams, and Jellies','active','seth','2025-05-23 13:40:19',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2034','Dried and Dehydrated Fruits, Vegetables, and Soup Mixes','active','seth','2025-05-23 13:40:20',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2035','Pickled Fruits and Vegetables, Vegetable Sauces and Seasonings, and Salad Dressings','active','seth','2025-05-23 13:40:20',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2037','Frozen Fruits, Fruit Juices, and Vegetables','active','seth','2025-05-23 13:40:20',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2038','Frozen Specialties, Not Elsewhere Classified','active','seth','2025-05-23 13:40:21',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2041','Flour and Other Grain Mill Products','active','seth','2025-05-23 13:40:21',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2043','Cereal Breakfast Foods','active','seth','2025-05-23 13:40:21',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2044','Rice Milling','active','seth','2025-05-23 13:40:22',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2045','Prepared Flour Mixes and Doughs','active','seth','2025-05-23 13:40:22',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2046','Wet Corn Milling','active','seth','2025-05-23 13:40:22',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2047','Dog and Cat Food','active','seth','2025-05-23 13:40:23',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2048','Prepared Feed and Feed Ingredients for Animals and Fowls, Except Dogs and Cats','active','seth','2025-05-23 13:40:23',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2051','Bread and Other Bakery Products, Except Cookies and Crackers','active','seth','2025-05-23 13:40:23',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2052','Cookies and Crackers','active','seth','2025-05-23 13:40:24',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2053','Frozen Bakery Products, Except Bread','active','seth','2025-05-23 13:40:24',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2061','Cane Sugar, Except Refining','active','seth','2025-05-23 13:40:24',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2062','Cane Sugar Refining','active','seth','2025-05-23 13:40:25',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2063','Beet Sugar','active','seth','2025-05-23 13:40:25',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2064','Candy and Other Confectionery Products','active','seth','2025-05-23 13:40:25',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2066','Chocolate and Cocoa Products','active','seth','2025-05-23 13:40:26',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2067','Chewing Gum','active','seth','2025-05-23 13:40:26',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2068','Salted and Roasted Nuts and Seeds','active','seth','2025-05-23 13:40:26',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2074','Cottonseed Oil Mills','active','seth','2025-05-23 13:40:27',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2075','Soybean Oil Mills','active','seth','2025-05-23 13:40:27',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2076','Vegetable Oil Mills, Except Corn, Cottonseed, and Soybean','active','seth','2025-05-23 13:40:27',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2077','Animal and Marine Fats and Oils','active','seth','2025-05-23 13:40:28',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2079','Shortening, Table Oils, Margarine, and Other Edible Fats and Oils, Not Elsewhere Classified','active','seth','2025-05-23 13:40:28',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2082','Malt Beverages','active','seth','2025-05-23 13:40:28',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2083','Malt','active','seth','2025-05-23 13:40:29',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2084','Wines, Brandy, and Brandy Spirits','active','seth','2025-05-23 13:40:29',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2085','Distilled and Blended Liquors','active','seth','2025-05-23 13:40:29',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2086','Bottled and Canned Soft Drinks and Carbonated Waters','active','seth','2025-05-23 13:40:30',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2087','Flavoring Extracts and Flavoring Syrups, Not Elsewhere Classified','active','seth','2025-05-23 13:40:30',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2091','Canned and Cured Fish and Seafoods','active','seth','2025-05-23 13:40:30',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2092','Prepared Fresh or Frozen Fish and Seafoods','active','seth','2025-05-23 13:40:31',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2095','Roasted Coffee','active','seth','2025-05-23 13:40:31',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2096','Potato Chips, Corn Chips, and Similar Snacks','active','seth','2025-05-23 13:40:31',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2097','Manufactured Ice','active','seth','2025-05-23 13:40:32',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2098','Macaroni, Spaghetti, Vermicelli, and Noodles','active','seth','2025-05-23 13:40:32',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2099','Food Preparations, Not Elsewhere Classified','active','seth','2025-05-23 13:40:32',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2111','Cigarettes','active','seth','2025-05-23 13:40:33',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2121','Cigars','active','seth','2025-05-23 13:40:33',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2131','Chewing and Smoking Tobacco and Snuff','active','seth','2025-05-23 13:40:33',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2141','Tobacco Stemming and Redrying','active','seth','2025-05-23 13:40:34',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2211','Broadwoven Fabric Mills, Cotton','active','seth','2025-05-23 13:40:34',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2221','Broadwoven Fabric Mills, Manmade Fiber and Silk','active','seth','2025-05-23 13:40:34',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2231','Broadwoven Fabric Mills, Wool (Including Dyeing and Finishing)','active','seth','2025-05-23 13:40:35',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2241','Narrow Fabric and Other Smallware Mills: Cotton, Wool, Silk, and Manmade Fiber','active','seth','2025-05-23 13:40:35',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2251','Women\'s Full-Length and Knee-Length Hosiery, Except Socks','active','seth','2025-05-23 13:40:35',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2252','Hosiery, Not Elsewhere Classified','active','seth','2025-05-23 13:40:36',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2253','Knit Outerwear Mills','active','seth','2025-05-23 13:40:36',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2254','Knit Underwear and Nightwear Mills','active','seth','2025-05-23 13:40:36',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2257','Weft Knit Fabric Mills','active','seth','2025-05-23 13:40:37',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2258','Lace and Warp Knit Fabric Mills','active','seth','2025-05-23 13:40:37',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2259','Knitting Mills, Not Elsewhere Classified','active','seth','2025-05-23 13:40:37',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2261','Finishers of Broadwoven Fabrics of Cotton','active','seth','2025-05-23 13:40:38',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2262','Finishers of Broadwoven Fabrics of Manmade Fiber and Silk','active','seth','2025-05-23 13:40:38',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2269','Finishers of Textiles, Not elsewhere Classified','active','seth','2025-05-23 13:40:38',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2273','Carpets and Rugs','active','seth','2025-05-23 13:40:39',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2281','Yarn Spinning Mills','active','seth','2025-05-23 13:40:39',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2282','Yarn Texturizing, Throwing, Twisting, and Winding Mills','active','seth','2025-05-23 13:40:39',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2284','Thread Mills','active','seth','2025-05-23 13:40:40',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2295','Coated Fabrics, Not Rubberized','active','seth','2025-05-23 13:40:40',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2296','Tire Cord and Fabrics','active','seth','2025-05-23 13:40:40',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2297','Non-woven Fabrics','active','seth','2025-05-23 13:40:41',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2298','Cordage and Twine','active','seth','2025-05-23 13:40:41',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2299','Textile goods, Not Elsewhere Classified','active','seth','2025-05-23 13:40:41',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2311','Men\'s and Boys\' Suits, Coats, and Overcoats','active','seth','2025-05-23 13:40:42',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2321','Men\'s and Boys\' Shirts, Except Work Shirts','active','seth','2025-05-23 13:40:42',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2322','Men\'s and Boys\' Underwear and Nightwear','active','seth','2025-05-23 13:40:42',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2323','Men\'s and Boys\' Neckwear','active','seth','2025-05-23 13:40:43',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2325','Men\'s and Boys\' Separate Trousers and Slacks','active','seth','2025-05-23 13:40:43',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2326','Men\'s and Boys\' Work Clothing','active','seth','2025-05-23 13:40:43',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2329','Men\'s and Boys\' Clothing, Not Elsewhere Classified','active','seth','2025-05-23 13:40:44',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2331','Women\'s, Misses\', and Juniors\' Blouses and Shirts','active','seth','2025-05-23 13:40:44',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2335','Women\'s, Misses\', and Juniors\' Dresses','active','seth','2025-05-23 13:40:44',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2337','Women\'s, Misses\', and Juniors\' Suits, Skirts, and Coats','active','seth','2025-05-23 13:40:45',NULL,NULL);
INSERT INTO sic_code (code,industry_title,status_cd,create_user,create_dt,update_user,update_dt) VALUES ('2339','Women\'s, Misses\', and Juniors\' Outerwear, Not Elsewhere Classified','active','seth','2025-05-23 13:40:47',NULL,NULL);
